public class mya_products{
  @AuraEnabled public String AssetId;
  @AuraEnabled public String ProductImage;
  @AuraEnabled public String ProductDesc;
  @AuraEnabled public String NickName; 
  @AuraEnabled public Boolean IsConsumerReady;
  @AuraEnabled public Boolean IsValidAsset; 
  @AuraEnabled public String ModelNumber;
  @AuraEnabled public String ConnectionStatus;
  @AuraEnabled public Boolean onlineStatus;
  @AuraEnabled public Boolean isconnectable;
  
  
    
  
 
}