@isTest
public class TriggerDuctlessTest {
    static testMethod void testTriggerDuctless2()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless3()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless4()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless5()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4,Model5';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4,Serial5';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless6()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4,Model5,Model6';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4,Serial5,Serial6';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless7()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4,Model5,Model6,Model7';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4,Serial5,Serial6,Serial7';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless8()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4,Model5,Model6,Model7,Model8';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4,Serial5,Serial6,Serial7,Serial8';
		insert ductrec;
		
    }
static testMethod void testTriggerDuctless9()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4,Model5,Model6,Model7,Model8,Model9';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4,Serial5,Serial6,Serial7,Serial8,Serial9';
		insert ductrec;
		
    }
    static testMethod void testTriggerDuctless10()
	{
        Ductless_product_registration__c ductrec = new Ductless_product_registration__c();
        ductrec.DATA_SOURCE_CODE__C = 'DG';
        ductrec.CONTRACTOR_CITY__C = 'Bangalore';
        ductrec.CONTRACTOR_COUNTRY__C = 'United States';
        ductrec.CONTRACTOR_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.CONTRACTOR_LAST_NAME__C = '';
        ductrec.CONTRACTOR_NAME__C = 'ContractorName1';
        ductrec.CONTRACTOR_PHONE_NUMBER__C = '(222) 222 2222';
        ductrec.CONTRACTOR_STATE__C = 'Calorado';
        ductrec.CONTRACTOR_STREET_1__C = 'ContractorAddress1';
        ductrec.CONTRACTOR_STREET_2__C = 'ContractorAddress2';
        ductrec.CONTRACTOR_ZIP_CODE__C = '560076';
        ductrec.DISTRIBUTOR_CITY__C = 'Bangalore';
        ductrec.DISTRIBUTOR_COUNTRY__C = 'Canada';
        ductrec.DISTRIBUTOR_FIRST_NAME__C = 'DistributorName1';
        ductrec.DISTRIBUTOR_STATE__C = 'Manitoba';
        ductrec.DISTRIBUTOR_STREET_1__C = 'DistributorAddress1';
        ductrec.DISTRIBUTOR_STREET_2__C = 'DistributorAddress2';
        ductrec.DISTRIBUTOR_ZIP_CODE__C = '560076';
        ductrec.OWNER_CITY__C = 'Bangalore';
        ductrec.OWNER_COUNTRY__C = 'United States';
        ductrec.OWNER_EMAIL_ADDRESS__C = 'abc321@abc.com';
        ductrec.OWNER_FIRST_NAME__C = 'Gowsic';
        ductrec.OWNER_LAST_NAME__C = 'S';
        ductrec.OWNER_PHONE_NUMBER__C = '(111) 111 1111';
        ductrec.OWNER_STATE__C = 'Calorado';
        ductrec.OWNER_STREET_1__C = 'OwnerInstallationAddress1';
        ductrec.OWNER_STREET_2__C = 'OwnerInstallationAddress2';
        ductrec.OWNER_ZIP_CODE__C = '560076';
        ductrec.OUTDOOR_UNIT_MODEL__C = 'Model1,Model2,Model3,Model4,Model5,Model6,Model7,Model8,Model9,Model10';
        ductrec.OUTDOOR_UNIT_SERIAL__C = 'Serial1,Serial2,Serial3,Serial4,Serial5,Serial6,Serial7,Serial8,Serial9,Serial10';
		insert ductrec;
		
    }
}